name: CI
on:
    pull_request:
        paths-ignore:
            - 'docs/**'
            - 'example/**'
        branches: [main]
jobs:
    ci:
        name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: ['16.x', '18.x']
                os: [ubuntu-latest, windows-latest, macOS-latest]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Use Node ${{ matrix.node }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}

            - name: Install pnpm 8.6.7
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 8.6.7

            - name: Install pnpm dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1

            - name: Lint
              run: pnpm lint

            - name: Test
              run: pnpm test:ci

            - name: Build
              run: pnpm build
