name: size
on:
    pull_request:
        paths-ignore:
            - 'docs/**'
            - 'example/**'
        branches: [main]
jobs:
    size:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1

            - name: Install pnpm 8.6.7
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 8.6.7

            - uses: andresz1/size-limit-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
