name: size
on:
    pull_request:
        paths-ignore:
            - 'docs/**'
            - 'example/**'
        branches: [main]
jobs:
    size:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v2

            - name: Install pnpm 8.6.7
              uses: pnpm/action-setup@v2.2.4
              with:
                  version: 8.6.7

            - name: Install pnpm dependencies (with cache)
              uses: covbot/pnpm-install-with-cache@v1

            # FIXME: This CI fails because there is no @types/lodash package in main branch
            - uses: andresz1/size-limit-action@v1.7.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  skip_step: install
                  script: pnpm cross-env NODE_OPTIONS=--openssl-legacy-provider pnpm size-limit --json
